#!/usr/bin/env python3
"""Capture reproducible environment locks and model fingerprints for this repo."""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import re
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Sequence


ROOT = Path(__file__).resolve().parents[1]
PORTABLE_LOCAL_FILE_PACKAGES = {"pip", "setuptools", "wheel"}
ROS_APT_PACKAGES = (
    "python3-colcon-common-extensions",
    "python3-numpy",
    "python3-opencv",
    "python3-scipy",
    "python3-yaml",
    "ros-jazzy-builtin-interfaces",
    "ros-jazzy-nav-msgs",
    "ros-jazzy-ros-base",
    "ros-jazzy-rosbag2-py",
    "ros-jazzy-rosbag2-storage-sqlite3",
    "ros-jazzy-rosidl-runtime-py",
    "ros-jazzy-sensor-msgs",
    "ros-jazzy-tf2-msgs",
)
MODEL_FILES = (
    ("locate_config", "models--nvidia--LocateAnything-3B/resolved/config.json"),
    ("locate_index", "models--nvidia--LocateAnything-3B/resolved/model.safetensors.index.json"),
    ("locate_shard_1", "models--nvidia--LocateAnything-3B/resolved/model-00001-of-00002.safetensors"),
    ("locate_shard_2", "models--nvidia--LocateAnything-3B/resolved/model-00002-of-00002.safetensors"),
    ("hamer_model_config", "hamer/_DATA/hamer_ckpts/model_config.yaml"),
    ("hamer_checkpoint", "hamer/_DATA/hamer_ckpts/checkpoints/new_hamer_weights.ckpt"),
    ("mano_right", "hamer/_DATA/data/mano/MANO_RIGHT.pkl"),
)


def run(args: Sequence[str], *, check: bool = True) -> str:
    proc = subprocess.run(args, cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if check and proc.returncode != 0:
        raise RuntimeError(f"Command failed ({proc.returncode}): {' '.join(args)}\n{proc.stderr.strip()}")
    return proc.stdout.strip()


def conda_python(env_name: str, code: str) -> str:
    return run(["conda", "run", "-n", env_name, "python", "-c", code])


def distribution_versions(env_name: str, purelib: str) -> Dict[str, str]:
    code = (
        "import importlib.metadata as m,json,sys; "
        "rows={}; "
        "[(rows.setdefault((d.metadata.get('Name') or '').lower().replace('_','-'),d.version)) "
        "for d in m.distributions(path=[sys.argv[1]]) if d.metadata.get('Name')]; "
        "print(json.dumps(rows,sort_keys=True))"
    )
    return json.loads(run(["conda", "run", "-n", env_name, "python", "-c", code, purelib]))


def capture_pip_lock(env_name: str, output: Path) -> Dict[str, object]:
    purelib = conda_python(env_name, "import sysconfig; print(sysconfig.get_paths()['purelib'])")
    raw = run(
        [
            "conda",
            "run",
            "-n",
            env_name,
            "python",
            "-m",
            "pip",
            "freeze",
            "--all",
            "--path",
            purelib,
        ]
    )
    versions = distribution_versions(env_name, purelib)
    locked: List[str] = []
    excluded_editables: List[str] = []
    excluded_local_files: List[str] = []
    pending_comment: str | None = None
    for raw_line in raw.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("# Editable install"):
            pending_comment = line[2:].strip()
            continue
        if line.startswith("-e "):
            excluded_editables.append(f"{pending_comment or 'editable install'}: {line[3:]}")
            pending_comment = None
            continue
        pending_comment = None
        file_match = re.match(r"^([^@]+?)\s*@\s*file://", line)
        if file_match:
            display_name = file_match.group(1).strip()
            key = display_name.lower().replace("_", "-")
            if key not in PORTABLE_LOCAL_FILE_PACKAGES:
                excluded_local_files.append(line)
                continue
            version = versions.get(key)
            if not version:
                raise RuntimeError(f"Cannot resolve installed version for local-file package: {line}")
            line = f"{display_name}=={version}"
        locked.append(line)

    header = [
        f"# Exact pip lock captured from Conda env: {env_name}",
        "# Generated by scripts/capture_environment_locks.py.",
        "# ROS packages inherited through PYTHONPATH are intentionally excluded.",
    ]
    if excluded_editables or excluded_local_files:
        header.append("# Non-portable local installs excluded and recorded in environment-info.json.")
    output.write_text("\n".join(header + [""] + locked) + "\n", encoding="utf-8")
    return {
        "environment": env_name,
        "python": conda_python(env_name, "import platform; print(platform.python_version())"),
        "purelib": purelib,
        "locked_packages": len(locked),
        "excluded_editables": excluded_editables,
        "excluded_local_file_installs": excluded_local_files,
    }


def capture_ros_lock(output: Path) -> Dict[str, object]:
    query = "${binary:Package}=${Version}\\n"
    lines: List[str] = []
    missing: List[str] = []
    for package in ROS_APT_PACKAGES:
        proc = subprocess.run(
            ["dpkg-query", "-W", f"-f={query}", package],
            cwd=ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        if proc.returncode == 0 and proc.stdout.strip():
            lines.append(proc.stdout.strip())
        else:
            missing.append(package)
    header = [
        "# Exact apt/ROS packages used by the ROS2 extraction environment.",
        "# Generated by scripts/capture_environment_locks.py on Ubuntu 24.04 / ROS Jazzy.",
        "# Reinstall with apt versions appropriate to an available matching repository snapshot.",
        "",
    ]
    output.write_text("\n".join(header + sorted(lines)) + "\n", encoding="utf-8")
    return {"locked_packages": len(lines), "missing_packages": missing}


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(8 * 1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def model_fingerprints(skip_hashes: bool) -> Dict[str, object]:
    rows: Dict[str, object] = {}
    for label, rel in MODEL_FILES:
        path = ROOT / rel
        if not path.is_file():
            rows[label] = {"path": rel, "exists": False}
            continue
        rows[label] = {
            "path": rel,
            "exists": True,
            "bytes": path.stat().st_size,
            "sha256": None if skip_hashes else sha256_file(path),
        }
    return rows


def torch_runtime(env_name: str) -> Dict[str, object]:
    code = (
        "import json,platform,torch,torchvision; "
        "print(json.dumps({'python':platform.python_version(),'torch':torch.__version__,"
        "'torchvision':torchvision.__version__,'torch_cuda':torch.version.cuda,"
        "'cudnn':torch.backends.cudnn.version(),'cuda_available':torch.cuda.is_available()}))"
    )
    return json.loads(conda_python(env_name, code))


def gpu_info() -> List[Dict[str, str]]:
    if shutil.which("nvidia-smi") is None:
        return []
    text = run(
        [
            "nvidia-smi",
            "--query-gpu=name,driver_version,memory.total",
            "--format=csv,noheader,nounits",
        ],
        check=False,
    )
    rows = []
    for line in text.splitlines():
        parts = [part.strip() for part in line.split(",")]
        if len(parts) == 3:
            rows.append({"name": parts[0], "driver_version": parts[1], "memory_mib": parts[2]})
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skip_model_hashes", action="store_true", help="Record model paths/sizes without reading large files.")
    args = parser.parse_args()

    locate = capture_pip_lock("locate_anything", ROOT / "requirements-locate.lock")
    hamer = capture_pip_lock("hamer", ROOT / "requirements-hamer.lock")
    ros = capture_ros_lock(ROOT / "requirements-ros-system.txt")

    os_release = {}
    release_path = Path("/etc/os-release")
    if release_path.is_file():
        for line in release_path.read_text(encoding="utf-8").splitlines():
            if "=" in line:
                key, value = line.split("=", 1)
                os_release[key] = value.strip().strip('"')

    nvcc = run(["nvcc", "--version"], check=False) if shutil.which("nvcc") else None
    git_commit = run(["git", "rev-parse", "HEAD"], check=False) or None
    payload = {
        "schema_version": 1,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "generator": "scripts/capture_environment_locks.py",
        "git_commit_at_capture": git_commit,
        "platform": {
            "os": os_release.get("PRETTY_NAME"),
            "kernel": platform.release(),
            "architecture": platform.machine(),
            "system_python": run(["/usr/bin/python3", "--version"], check=False),
            "conda": run(["conda", "--version"], check=False),
            "ros_distro": "jazzy" if Path("/opt/ros/jazzy").is_dir() else None,
        },
        "gpu": gpu_info(),
        "cuda": {"nvcc": nvcc, "nvcc_available": nvcc is not None},
        "conda_environments": {
            "locate_anything": {**locate, "runtime": torch_runtime("locate_anything")},
            "hamer": {**hamer, "runtime": torch_runtime("hamer")},
        },
        "ros_system": ros,
        "models": model_fingerprints(args.skip_model_hashes),
    }
    (ROOT / "environment-info.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps({
        "locate_locked": locate["locked_packages"],
        "hamer_locked": hamer["locked_packages"],
        "ros_locked": ros["locked_packages"],
        "model_hashes_skipped": args.skip_model_hashes,
    }, ensure_ascii=False))


if __name__ == "__main__":
    main()
